create table "CURSONORMADM"."TRES_RESERVA" (
   "ID_RESERVA"           number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment
   by 1 start with 1 cache 20 noorder nocycle nokeep noscale,
   "ID_RECURSO"           number not null,
   "HORA_INICIO"          number not null,
   "MINUTO_INICIO"        number not null,
   "MINUTOS_RESERVA"      number not null,
   "FECHA_RESERVA"        date not null,
   "FECHA_CREACION"       date default sysdate not null,
   "FECHA_CONFIRMACION"   date,
   "FECHA_MODIFICACION"   date,
   "OBSERVACIONES"        varchar2(1000) collate "USING_NLS_COMP",
   "CODPER"               number,
   "ACTIVO"               varchar2(1) default 'S' not null,
   "USUARIO_CREACION"     varchar2(50),
   "USUARIO_MODIFICACION" varchar2(50),
   constraint "CK_TRES_RESERVA_ID_RESERVA_NN" check ( "ID_RESERVA" is not null ) enable,
   constraint "CK_TRES_RESERVA_ID_RECURSO_NN" check ( "ID_RECURSO" is not null ) enable,
   constraint "CK_TRES_RESERVA_HORA_INICIO_NN" check ( "HORA_INICIO" is not null ) enable,
   constraint "CK_TRES_RESERVA_MINUTO_INI_NN" check ( "MINUTO_INICIO" is not null ) enable,
   constraint "CK_TRES_RESERVA_MINUTOS_NN" check ( "MINUTOS_RESERVA" is not null ) enable,
   constraint "CK_TRES_RESERVA_FECHA_RES_NN" check ( "FECHA_RESERVA" is not null ) enable,
   constraint "CK_TRES_RESERVA_FECHA_CRE_NN" check ( "FECHA_CREACION" is not null ) enable,
   constraint "CK_TRES_RESERVA_ACTIVO_NN" check ( "ACTIVO" is not null ) enable,
   constraint "CK_TRES_RESERVA_HORA_INICIO" check ( hora_inicio between 0 and 23 ) enable,
   constraint "CK_TRES_RESERVA_MINUTO_INICIO" check ( minuto_inicio between 0 and 59 ) enable,
   constraint "CK_TRES_RESERVA_MINUTOS" check ( minutos_reserva > 0 ) enable,
   constraint "CK_TRES_RESERVA_ACTIVO"
      check ( activo in ( 'S',
                          'N' ) ) enable,
   constraint "PK_TRES_RESERVA" primary key ( "ID_RESERVA" )
      using index enable,
   constraint "FK_TRES_RESERVA_RECURSO" foreign key ( "ID_RECURSO" )
      references "CURSONORMADM"."TRES_RECURSO" ( "ID_RECURSO" )
   enable
) default collation "USING_NLS_COMP";

comment on table "CURSONORMADM"."TRES_RESERVA" is
   'Reservas base de la aplicacion, con recurso, titular, fecha, hora, duracion y observaciones generales.';

comment on column "CURSONORMADM"."TRES_RESERVA"."ID_RESERVA" is
   'Identificador unico de la reserva. Clave primaria generada automaticamente.';
comment on column "CURSONORMADM"."TRES_RESERVA"."ID_RECURSO" is
   'Identificador del recurso reservado. FK a TRES_RECURSO.';
comment on column "CURSONORMADM"."TRES_RESERVA"."HORA_INICIO" is
   'Hora de inicio de la reserva en formato de 24 horas (0-23).';
comment on column "CURSONORMADM"."TRES_RESERVA"."MINUTO_INICIO" is
   'Minuto de inicio de la reserva (0-59).';
comment on column "CURSONORMADM"."TRES_RESERVA"."MINUTOS_RESERVA" is
   'Duracion total de la reserva expresada en minutos. Debe ser mayor que 0.';
comment on column "CURSONORMADM"."TRES_RESERVA"."FECHA_RESERVA" is
   'Fecha en la que se realiza la reserva.';
comment on column "CURSONORMADM"."TRES_RESERVA"."FECHA_CREACION" is
   'Fecha de creacion del registro. Se inicializa con SYSDATE por defecto.';
comment on column "CURSONORMADM"."TRES_RESERVA"."FECHA_CONFIRMACION" is
   'Fecha en que se confirmo la reserva. Nulo si la reserva aun no ha sido confirmada.';
comment on column "CURSONORMADM"."TRES_RESERVA"."FECHA_MODIFICACION" is
   'Fecha de la ultima modificacion del registro.';
comment on column "CURSONORMADM"."TRES_RESERVA"."OBSERVACIONES" is
   'Texto libre con observaciones o notas adicionales sobre la reserva.';
comment on column "CURSONORMADM"."TRES_RESERVA"."CODPER" is
   'Codigo de la persona titular de la reserva. Referencia al directorio de personas de la UA.';
comment on column "CURSONORMADM"."TRES_RESERVA"."ACTIVO" is
   'Indicador de borrado logico. S=activo, N=eliminado.';
comment on column "CURSONORMADM"."TRES_RESERVA"."USUARIO_CREACION" is
   'Identificador del usuario que creo el registro.';
comment on column "CURSONORMADM"."TRES_RESERVA"."USUARIO_MODIFICACION" is
   'Identificador del usuario que realizo la ultima modificacion.';