create table cursonormadm.tres_recurso (
   id_recurso            number generated by default on null as identity
      constraint ck_tres_recurso_id_nn not null,
   nombre_es             varchar2(200)
      constraint ck_tres_recurso_nombre_es_nn not null,
   nombre_ca             varchar2(200)
      constraint ck_tres_recurso_nombre_ca_nn not null,
   nombre_en             varchar2(200)
      constraint ck_tres_recurso_nombre_en_nn not null,
   descripcion_es        clob,
   descripcion_ca        clob,
   descripcion_en        clob,
   fecha_modificacion    date default sysdate
      constraint ck_tres_recurso_fecha_mod_nn not null,
   granulidad            number,
   duracion              number,
   id_tipo_recurso       number,
   activo                varchar2(1) default 'S'
      constraint ck_tres_recurso_activo_nn not null,
   visible               varchar2(1) default 'S'
      constraint ck_tres_recurso_visible_nn not null,
   atiende_misma_persona varchar2(1) default 'N'
      constraint ck_tres_recurso_atiende_nn not null,
   constraint pk_tres_recurso primary key ( id_recurso ),
   constraint fk_tres_recurso_tipo_recurso foreign key ( id_tipo_recurso )
      references cursonormadm.tres_tipo_recurso ( id_tipo_recurso ),
   constraint ck_tres_recurso_activo check ( activo in ( 'S',
                                                         'N' ) ),
   constraint ck_tres_recurso_visible check ( visible in ( 'S',
                                                           'N' ) )
);