-- =============================================================================
-- SETUP COMPLETO — CURSONORMADM
-- Schema ReserUA · Curso de normalización 2026
-- Ejecutar conectado como CURSONORMADM
-- =============================================================================
-- ORDEN LÓGICO:
--   1. DROP en orden inverso a la FK (primero hijos, luego padres)
--   2. CREATE en orden de dependencia (primero padres, luego hijos)
--   3. INSERT en el mismo orden (primero TRES_TIPO_RECURSO, luego TRES_RECURSO)
-- =============================================================================


-- -----------------------------------------------------------------------------
-- PASO 1 — DROP (hijo → padre para respetar la FK)
-- -----------------------------------------------------------------------------

drop table cursonormadm.tres_recurso cascade constraints purge;
drop table cursonormadm.tres_tipo_recurso cascade constraints purge;


-- -----------------------------------------------------------------------------
-- PASO 2 — CREATE (padre → hijo)
-- -----------------------------------------------------------------------------

-- Padre: catálogo de tipos. Sin ACTIVO ni borrado lógico.
create table cursonormadm.tres_tipo_recurso (
   id_tipo_recurso number generated by default on null as identity
      constraint ck_tres_tipo_recurso_id_nn not null,
   codigo          varchar2(100)
      constraint ck_tres_tipo_recurso_codigo_nn not null,
   nombre_es       varchar2(150)
      constraint ck_tres_tipo_recurso_nombre_es_nn not null,
   nombre_ca       varchar2(150)
      constraint ck_tres_tipo_recurso_nombre_ca_nn not null,
   nombre_en       varchar2(150)
      constraint ck_tres_tipo_recurso_nombre_en_nn not null,
   constraint pk_tres_tipo_recurso primary key ( id_tipo_recurso ),
   constraint uk_tres_tipo_recurso_codigo unique ( codigo )
);

-- Hijo: recursos reservables. FK a TRES_TIPO_RECURSO. Con borrado lógico (ACTIVO/VISIBLE).
create table cursonormadm.tres_recurso (
   id_recurso            number generated by default on null as identity
      constraint ck_tres_recurso_id_nn not null,
   nombre_es             varchar2(200)
      constraint ck_tres_recurso_nombre_es_nn not null,
   nombre_ca             varchar2(200)
      constraint ck_tres_recurso_nombre_ca_nn not null,
   nombre_en             varchar2(200)
      constraint ck_tres_recurso_nombre_en_nn not null,
   descripcion_es        clob,
   descripcion_ca        clob,
   descripcion_en        clob,
   fecha_modificacion    date default sysdate
      constraint ck_tres_recurso_fecha_mod_nn not null,
   granulidad            number,
   duracion              number,
   id_tipo_recurso       number,
   activo                varchar2(1) default 'S'
      constraint ck_tres_recurso_activo_nn not null,
   visible               varchar2(1) default 'S'
      constraint ck_tres_recurso_visible_nn not null,
   atiende_misma_persona varchar2(1) default 'N'
      constraint ck_tres_recurso_atiende_nn not null,
   constraint pk_tres_recurso primary key ( id_recurso ),
   constraint fk_tres_recurso_tipo_recurso foreign key ( id_tipo_recurso )
      references cursonormadm.tres_tipo_recurso ( id_tipo_recurso ),
   constraint ck_tres_recurso_activo check ( activo in ( 'S',
                                                         'N' ) ),
   constraint ck_tres_recurso_visible check ( visible in ( 'S',
                                                           'N' ) )
);


-- -----------------------------------------------------------------------------
-- PASO 3 — INSERT (padre primero; hijo usa subquery sobre CODIGO de TRES_TIPO_RECURSO)
-- -----------------------------------------------------------------------------

-- ── TRES_TIPO_RECURSO ────────────────────────────────────────────────────────

insert into cursonormadm.tres_tipo_recurso (
   codigo,
   nombre_es,
   nombre_ca,
   nombre_en
) values ( 'AULA',
           'Aula',
           'Aula',
           'Classroom' );

insert into cursonormadm.tres_tipo_recurso (
   codigo,
   nombre_es,
   nombre_ca,
   nombre_en
) values ( 'LABORATORIO',
           'Laboratorio',
           'Laboratori',
           'Laboratory' );

insert into cursonormadm.tres_tipo_recurso (
   codigo,
   nombre_es,
   nombre_ca,
   nombre_en
) values ( 'SALA_REUNIONES',
           'Sala de reuniones',
           'Sala de reunions',
           'Meeting room' );

insert into cursonormadm.tres_tipo_recurso (
   codigo,
   nombre_es,
   nombre_ca,
   nombre_en
) values ( 'DESPACHO',
           'Despacho',
           'Despatx',
           'Office' );

insert into cursonormadm.tres_tipo_recurso (
   codigo,
   nombre_es,
   nombre_ca,
   nombre_en
) values ( 'SALA_INFORMATICA',
           'Sala de informática',
           'Sala d''informàtica',
           'Computer room' );

insert into cursonormadm.tres_tipo_recurso (
   codigo,
   nombre_es,
   nombre_ca,
   nombre_en
) values ( 'AUDITORIO',
           'Auditorio',
           'Auditori',
           'Auditorium' );

insert into cursonormadm.tres_tipo_recurso (
   codigo,
   nombre_es,
   nombre_ca,
   nombre_en
) values ( 'SALA_ESTUDIO',
           'Sala de estudio',
           'Sala d''estudi',
           'Study room' );

insert into cursonormadm.tres_tipo_recurso (
   codigo,
   nombre_es,
   nombre_ca,
   nombre_en
) values ( 'ESPACIO_DEPORTIVO',
           'Instalación deportiva',
           'Instal·lació esportiva',
           'Sports facility' );

commit;

-- ── TRES_RECURSO ─────────────────────────────────────────────────────────────
-- ID_TIPO_RECURSO se resuelve por subquery: no depende del ID generado por IDENTITY.

-- AULA
insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Aula Magna',
           'Aula Magna',
           'Main Hall',
           'Aula de gran capacidad para actos académicos y conferencias. Aforo: 400 personas.',
           'Aula de gran capacitat per a actes acadèmics i conferències. Aforament: 400 persones.',
           'Large capacity hall for academic events and conferences. Capacity: 400 people.',
           60,
           120,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'AULA'
           ),
           'S',
           'S',
           'N',
           sysdate );

insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Aula 1.01 — Edificio A',
           'Aula 1.01 — Edifici A',
           'Room 1.01 — Building A',
           'Aula docente equipada con proyector y pizarra digital. Aforo: 60 personas.',
           'Aula docent equipada amb projector i pissarra digital. Aforament: 60 persones.',
           'Teaching room equipped with projector and smart board. Capacity: 60 people.',
           30,
           60,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'AULA'
           ),
           'S',
           'S',
           'N',
           sysdate );

insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Seminario 002 — Edificio B',
           'Seminari 002 — Edifici B',
           'Seminar Room 002 — Building B',
           'Sala seminario para grupos reducidos. Aforo: 25 personas. Disponible con reserva previa.',
           'Sala seminari per a grups reduïts. Aforament: 25 persones. Disponible amb reserva prèvia.',
           'Seminar room for small groups. Capacity: 25 people. Available on prior booking.',
           30,
           60,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'AULA'
           ),
           'S',
           'S',
           'N',
           sysdate );

insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Aula 3.12 — Edificio C (en obras)',
           'Aula 3.12 — Edifici C (en obres)',
           'Room 3.12 — Building C (under renovation)',
           'Aula temporalmente fuera de servicio por obras de renovación.',
           'Aula temporalment fora de servei per obres de renovació.',
           'Room temporarily out of service due to renovation works.',
           30,
           60,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'AULA'
           ),
           'N',
           'N',
           'N',
           sysdate );

-- LABORATORIO
insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Laboratorio de Química Orgánica',
           'Laboratori de Química Orgànica',
           'Organic Chemistry Laboratory',
           'Laboratorio equipado para prácticas de química orgánica. Aforo: 30 estudiantes. Requiere acreditación de seguridad.'
           ,
           'Laboratori equipat per a pràctiques de química orgànica. Aforament: 30 estudiants. Requereix acreditació de seguretat.'
           ,
           'Laboratory equipped for organic chemistry practicals. Capacity: 30 students. Safety accreditation required.',
           60,
           120,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'LABORATORIO'
           ),
           'S',
           'S',
           'S',
           sysdate );

insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Laboratorio de Física Experimental',
           'Laboratori de Física Experimental',
           'Experimental Physics Laboratory',
           'Laboratorio de física con equipos de medición de precisión. Aforo: 24 estudiantes.',
           'Laboratori de física amb equips de mesura de precisió. Aforament: 24 estudiants.',
           'Physics laboratory with precision measurement equipment. Capacity: 24 students.',
           60,
           120,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'LABORATORIO'
           ),
           'S',
           'S',
           'S',
           sysdate );

insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Laboratorio de Biología Molecular',
           'Laboratori de Biologia Molecular',
           'Molecular Biology Laboratory',
           'Laboratorio con equipamiento de biología molecular: PCR, electroforesis y microscopios. Aforo: 20 estudiantes.',
           'Laboratori amb equipament de biologia molecular: PCR, electroforesi i microscopis. Aforament: 20 estudiants.',
           'Laboratory with molecular biology equipment: PCR, electrophoresis and microscopes. Capacity: 20 students.',
           60,
           120,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'LABORATORIO'
           ),
           'S',
           'S',
           'S',
           sysdate );

-- SALA_REUNIONES
insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Sala de Juntas del Rectorado',
           'Sala de Juntes del Rectorat',
           'Rectorate Board Room',
           'Sala de representación institucional con videoconferencia integrada. Aforo: 20 personas.',
           'Sala de representació institucional amb videoconferència integrada. Aforament: 20 persones.',
           'Institutional representation room with integrated video conferencing. Capacity: 20 people.',
           30,
           60,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'SALA_REUNIONES'
           ),
           'S',
           'N',
           'N',
           sysdate );

insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Sala de Reuniones Decanato — Facultad de Ciencias',
           'Sala de Reunions Deganat — Facultat de Ciències',
           'Meeting Room — Faculty of Sciences Dean''s Office',
           'Sala de reuniones de uso interno del decanato. Aforo: 12 personas.',
           'Sala de reunions d''ús intern del deganat. Aforament: 12 persones.',
           'Internal meeting room for the dean''s office. Capacity: 12 people.',
           30,
           60,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'SALA_REUNIONES'
           ),
           'S',
           'N',
           'N',
           sysdate );

-- DESPACHO
insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Despacho de Tutorías A-201',
           'Despatx de Tutories A-201',
           'Tutorial Office A-201',
           'Despacho habilitado para tutorías y atención al estudiante. Aforo: 4 personas.',
           'Despatx habilitat per a tutories i atenció a l''estudiantat. Aforament: 4 persones.',
           'Office set up for tutorials and student support. Capacity: 4 people.',
           30,
           30,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'DESPACHO'
           ),
           'S',
           'S',
           'S',
           sysdate );

insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Despacho de Tutorías B-105',
           'Despatx de Tutories B-105',
           'Tutorial Office B-105',
           'Despacho compartido para tutorías. Disponible en horario de mañana. Aforo: 4 personas.',
           'Despatx compartit per a tutories. Disponible en horari de matí. Aforament: 4 persones.',
           'Shared office for tutorials. Available in the morning. Capacity: 4 people.',
           30,
           30,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'DESPACHO'
           ),
           'S',
           'S',
           'S',
           sysdate );

-- SALA_INFORMATICA
insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Sala de Informática 1 — Edificio Politécnica II',
           'Sala d''Informàtica 1 — Edifici Politècnica II',
           'Computer Room 1 — Polytechnic Building II',
           'Sala con 40 puestos equipados con Windows 11 y software de desarrollo. Aforo: 40 estudiantes.',
           'Sala amb 40 llocs equipats amb Windows 11 i programari de desenvolupament. Aforament: 40 estudiants.',
           'Room with 40 workstations running Windows 11 and development software. Capacity: 40 students.',
           60,
           120,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'SALA_INFORMATICA'
           ),
           'S',
           'S',
           'N',
           sysdate );

insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Sala de Informática 2 — Biblioteca General',
           'Sala d''Informàtica 2 — Biblioteca General',
           'Computer Room 2 — Main Library',
           'Sala de acceso libre con 30 equipos para trabajo de estudiantes. Aforo: 30 personas.',
           'Sala d''accés lliure amb 30 equips per a treball d''estudiants. Aforament: 30 persones.',
           'Open-access room with 30 computers for student use. Capacity: 30 people.',
           60,
           120,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'SALA_INFORMATICA'
           ),
           'S',
           'S',
           'N',
           sysdate );

-- AUDITORIO
insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Auditorio Principal del Campus',
           'Auditori Principal del Campus',
           'Main Campus Auditorium',
           'Auditorio con equipo de sonido profesional y sistema de traducción simultánea. Aforo: 500 personas.',
           'Auditori amb equip de so professional i sistema de traducció simultània. Aforament: 500 persones.',
           'Auditorium with professional sound equipment and simultaneous translation system. Capacity: 500 people.',
           60,
           120,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'AUDITORIO'
           ),
           'S',
           'S',
           'S',
           sysdate );

insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Sala de Actos — Facultad de Derecho',
           'Sala d''Actes — Facultat de Dret',
           'Event Hall — Faculty of Law',
           'Sala de actos con tarima y sistema audiovisual. Aforo: 200 personas.',
           'Sala d''actes amb tarima i sistema audiovisual. Aforament: 200 persones.',
           'Event hall with stage and audiovisual system. Capacity: 200 people.',
           60,
           120,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'AUDITORIO'
           ),
           'S',
           'S',
           'S',
           sysdate );

-- SALA_ESTUDIO
insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Sala de Estudio en Silencio — Biblioteca General',
           'Sala d''Estudi en Silenci — Biblioteca General',
           'Silent Study Room — Main Library',
           'Zona de estudio individual en silencio. Acceso con tarjeta universitaria. 80 puestos.',
           'Zona d''estudi individual en silenci. Accés amb targeta universitària. 80 llocs.',
           'Individual silent study area. Access with university card. 80 seats.',
           60,
           120,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'SALA_ESTUDIO'
           ),
           'S',
           'S',
           'N',
           sysdate );

insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Sala de Trabajo en Grupo A',
           'Sala de Treball en Grup A',
           'Group Study Room A',
           'Sala reservable para trabajo en grupo. Capacidad: 8 personas. Pizarra y pantalla.',
           'Sala reservable per a treball en grup. Capacitat: 8 persones. Pissarra i pantalla.',
           'Bookable room for group work. Capacity: 8 people. Whiteboard and screen.',
           60,
           120,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'SALA_ESTUDIO'
           ),
           'S',
           'S',
           'N',
           sysdate );

-- ESPACIO_DEPORTIVO
insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Pista de Pádel 1',
           'Pista de Pàdel 1',
           'Padel Court 1',
           'Pista de pádel cubierta. Reservable en franjas de 1 hora. Solo miembros de la comunidad universitaria.',
           'Pista de pàdel coberta. Reservable en franges d''1 hora. Només membres de la comunitat universitària.',
           'Indoor padel court. Bookable in 1-hour slots. University community members only.',
           60,
           60,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'ESPACIO_DEPORTIVO'
           ),
           'S',
           'S',
           'N',
           sysdate );

insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Pabellón Polideportivo — Pista Central',
           'Pavelló Poliesportiu — Pista Central',
           'Sports Hall — Main Court',
           'Pista polideportiva para baloncesto, voleibol y fútbol sala. Aforo: 300 espectadores.',
           'Pista poliesportiva per a bàsquet, voleibol i futbol sala. Aforament: 300 espectadors.',
           'Multi-sport court for basketball, volleyball and indoor football. Spectator capacity: 300.',
           60,
           60,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'ESPACIO_DEPORTIVO'
           ),
           'S',
           'S',
           'N',
           sysdate );

insert into cursonormadm.tres_recurso (
   nombre_es,
   nombre_ca,
   nombre_en,
   descripcion_es,
   descripcion_ca,
   descripcion_en,
   granulidad,
   duracion,
   id_tipo_recurso,
   activo,
   visible,
   atiende_misma_persona,
   fecha_modificacion
) values ( 'Piscina Cubierta',
           'Piscina Coberta',
           'Indoor Swimming Pool',
           'Piscina olímpica cubierta de 25 metros. Uso académico y libre para la comunidad universitaria.',
           'Piscina olímpica coberta de 25 metres. Ús acadèmic i lliure per a la comunitat universitària.',
           '25-metre indoor Olympic swimming pool. Academic and open use for the university community.',
           60,
           60,
           (
              select id_tipo_recurso
                from cursonormadm.tres_tipo_recurso
               where codigo = 'ESPACIO_DEPORTIVO'
           ),
           'N',
           'N',
           'N',
           sysdate );

commit;