CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_FRANJA_HORARIO_AGARLO" ("ID_FRANJA", "ID_RECURSO", "FECHA_INICIO", "FECHA_FIN", "ACTIVO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT 
  /* Vista de v_franja_horario.        
         
  2026- 06-11 Alicia Creación de la vista */
   ID_FRANJA,
   ID_RECURSO,
   FECHA_INICIO,
   FECHA_FIN,
   ACTIVO
   FROM CURSONORMADM.TRES_FRANJA_HORARIO;