CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_HORARIO_DIA_AGARLO" ("ID_HORARIO_DIA", "ID_FRANJA", "ID_RECURSO", "DIA", "HORA_INICIO", "MINUTO_INICIO", "HORA_FIN", "MINUTO_FIN", "BLOQUEADO", "ORDEN") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT 
  
  /* Vista de horarios por día para franjas y horarios genéricos de recurso.
   11/05//2026  Agarlo  Creación de la vista. */
  ID_HORARIO_DIA,
  ID_FRANJA,
  ID_RECURSO,
  DIA,
  HORA_INICIO,
  MINUTO_INICIO,
  HORA_FIN,
  MINUTO_FIN,
  BLOQUEADO,
  ORDEN
   FROM CURSONORMADM.TRES_HORARIO_DIA;