CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_HORARIO_DIA_JPUIG" ("ID_HORARIO_DIA", "ID_FRANJA", "ID_RECURSO", "DIA", "HORA_INICIO", "MINUTO_INICIO", "HORA_FIN", "MINUTO_FIN", "BLOQUEADO", "ORDEN", "NOMBRE_RECURSO_ES", "NOMBRE_RECURSO_CA", "NOMBRE_RECURSO_EN", "FECHA_INICIO", "FECHA_FIN") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT /* Vista que permite consultar los s franjas horarias asociadas
            a los recursos

         IMPORTANTE: ID_FRANJA e ID_RECURSO se usa para filtrar el recurso 
         y sus franjas por día

        20260511  JAVIER PUIG Creación de la vista
                       */
          THD.ID_HORARIO_DIA,
          THD.ID_FRANJA,
          THD.ID_RECURSO,
          THD.DIA,
          THD.HORA_INICIO,
          THD.MINUTO_INICIO,
          THD.HORA_FIN,
          THD.MINUTO_FIN,
          NVL (THD.BLOQUEADO, 'N') AS BLOQUEADO,
            THD.ORDEN,
          TR.NOMBRE_ES AS NOMBRE_RECURSO_ES,
          TR.NOMBRE_CA AS NOMBRE_RECURSO_CA,
          TR.NOMBRE_EN AS NOMBRE_RECURSO_EN,
          TFH.FECHA_INICIO,
          TFH.FECHA_FIN
     FROM CURSONORMADM.TRES_HORARIO_DIA THD
     LEFT JOIN CURSONORMADM.TRES_FRANJA_HORARIO TFH ON THD.ID_FRANJA = TFH.ID_FRANJA
     LEFT JOIN CURSONORMADM.TRES_RECURSO TR ON THD.ID_RECURSO = TR.ID_RECURSO;