CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_FRANJA_HORARIO_OPM" ("ID_FRANJA", "ID_RECURSO", "FECHA_INICIO", "FECHA_FIN", "ACTIVO", "NOMBRE_RECURSO_ES", "NOMBRE_RECURSO_CA", "NOMBRE_RECURSO_EN") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT /* Vista de franjas horarias asociadas a un recurso.

         IMPORTANTE: Expone nombres del recurso para evitar N+1 queries.
                     JOIN es INNER porque ID_RECURSO NOT NULL en TRES_FRANJA_HORARIO.
                     NVL(ACTIVO, 'N') garantiza flag consistente en aplicación.

 2026-05-11  Óscar Pina  Creación de la vista.
                       */
  FH.ID_FRANJA,
  FH.ID_RECURSO,
  FH.FECHA_INICIO,
  FH.FECHA_FIN,
  NVL(FH.ACTIVO, 'N') AS ACTIVO,
  RC.NOMBRE_ES AS NOMBRE_RECURSO_ES,
  RC.NOMBRE_CA AS NOMBRE_RECURSO_CA,
  RC.NOMBRE_EN AS NOMBRE_RECURSO_EN
FROM CURSONORMADM.TRES_FRANJA_HORARIO FH
INNER JOIN CURSONORMADM.TRES_RECURSO RC
  ON FH.ID_RECURSO = RC.ID_RECURSO;