CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_HORARIO_DIA_ANATOL" ("ID_HORARIO_DIA", "ID_FRANJA", "ID_RECURSO", "DIA", "HORA_INICIO", "MINUTO_INICIO", "HORA_FIN", "MINUTO_FIN", "ORDEN", "BLOQUEADO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT 
    -- Vista de TRES_HORARIO_DIA, para ver la configuración de horario para un recurso.
    -- IMPORTANTE: <invariante o decisión clave>. ESTO NO LO HE ENTENDIDO
    --   2026-05-11  Creación inicial de la vista por ANA AMELIA TOLOSA GONZÁLEZ
    
    ID_HORARIO_DIA,
    ID_FRANJA,
    ID_RECURSO,
    DIA,
    HORA_INICIO,
    MINUTO_INICIO,
    HORA_FIN,
    MINUTO_FIN,
    ORDEN,
    NVL(BLOQUEADO, 'N')
FROM CURSONORMADM.TRES_HORARIO_DIA;