CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_FRANJA_HORARIO_MAJOBLA" ("ID_FRANJA", "ID_RECURSO", "NOMBRE_ES", "NOMBRE_CA", "NOMBRE_EN", "FECHA_INICIO", "FECHA_FIN", "ACTIVO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
      FH.ID_FRANJA,
       FH.ID_RECURSO,
       R.NOMBRE_ES,
       R.NOMBRE_CA,
       R.NOMBRE_EN,
       FH.FECHA_INICIO,
       FH.FECHA_FIN,
       FH.ACTIVO
FROM CURSONORMADM.TRES_FRANJA_HORARIO FH
     JOIN CURSONORMADM.TRES_RECURSO R
         ON R.ID_RECURSO = FH.ID_RECURSO;