CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_FRANJA_HORARIO_SERGI" ("ID_FRANJA", "ID_RECURSO", "FECHA_INICIO", "FECHA_FIN", "ACTIVO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT /* Vista de franges horàries associades a un recurs

           IMPORTANT: 

   11/05/2026  Sergi
   
                       */
  ID_FRANJA,
  ID_RECURSO,
  FECHA_INICIO,
  FECHA_FIN,
  ACTIVO
FROM CURSONORMADM.TRES_FRANJA_HORARIO;