CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_FRANJA_HORARIO_PACOFER" ("ID_FRANJA", "ID_RECURSO", "FECHA_INICIO", "FECHA_FIN", "ACTIVO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT FH.ID_FRANJA,
       FH.ID_RECURSO,
       FH.FECHA_INICIO,
       FH.FECHA_FIN,
       FH.ACTIVO
  FROM CURSONORMADM.TRES_FRANJA_HORARIO FH;