CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_HORARIO_DIA_PACOFER" ("ID_HORARIO_DIA", "ID_FRANJA", "ID_RECURSO", "DIA", "HORA_INICIO", "MINUTO_INICIO", "HORA_FIN", "MINUTO_FIN", "BLOQUEADO", "ORDEN") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
       HD.ID_HORARIO_DIA,
       HD.ID_FRANJA,
       HD.ID_RECURSO,
       HD.DIA,
       HD.HORA_INICIO,
       HD.MINUTO_INICIO,
       HD.HORA_FIN,
       HD.MINUTO_FIN,
       NVL(HD.BLOQUEADO, 'N') AS BLOQUEADO,
       HD.ORDEN
FROM TRES_HORARIO_DIA HD;