CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_HORARIO_DIA_CANDE" ("ID_HORARIO_DIA", "ID_FRANJA", "ID_RECURSO", "NOMBRE_RECURSO_ES", "NOMBRE_RECURSO_VA", "NOMBRE_RECURSO_EN", "DIA", "HORA_INICIO", "MINUTO_INICIO", "HORA_FIN", "MINUTO_FIN", "BLOQUEADO", "ORDEN") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT /* Vista de horarios por día para franjas y horarios genéricos de recurso.
           IMPORTANTE: Expone tanto ID_FRANJA como ID_RECURSO para soportar horarios específicos y genéricos.
   13/05/2026  CANDE  Creación de la vista.
                       */
  H.ID_HORARIO_DIA,
  H.ID_FRANJA,
  H.ID_RECURSO,
  R.NOMBRE_ES,
  R.NOMBRE_CA,
  R.NOMBRE_EN,
  H.DIA,
  H.HORA_INICIO,
  H.MINUTO_INICIO,
  H.HORA_FIN,
  H.MINUTO_FIN,
  H.BLOQUEADO,
  H.ORDEN
FROM CURSONORMADM.TRES_HORARIO_DIA H 
LEFT JOIN CURSONORMADM.TRES_RECURSO R ON R.ID_RECURSO=H.ID_RECURSO;