CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_HORARIO_DIA_MARILOLT" ("ID_HORARIO_DIA", "ID_FRANJA", "ID_RECURSO", "DIA", "HORA_INICIO", "MINUTO_INICIO", "HORA_FIN", "MINUTO_FIN", "BLOQUEADO", "BLOQUEADO_NVL", "ORDEN", "FECHA_INICIO", "FECHA_FIN", "NOMBRE_ES", "NOMBRE_CA", "NOMBRE_EN") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
hd.ID_HORARIO_DIA,
hd.ID_FRANJA,
hd.ID_RECURSO,
hd.DIA,
hd.HORA_INICIO,
hd.MINUTO_INICIO,
hd.HORA_FIN,
hd.MINUTO_FIN,
hd.BLOQUEADO,
NVL(hd.BLOQUEADO,'N') AS BLOQUEADO_NVL,
hd.ORDEN,
f.FECHA_INICIO,
f.FECHA_FIN,
r.NOMBRE_ES,
r.NOMBRE_CA,
R.NOMBRE_EN
FROM TRES_HORARIO_DIA hd
LEFT JOIN TRES_FRANJA_HORARIO f ON hd.ID_FRANJA = f.ID_FRANJA
LEFT JOIN TRES_RECURSO r ON hd.ID_RECURSO = r.ID_RECURSO;