CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_FRANJA_HORARIO_ANATOL" ("ID_FRANJA", "ID_RECURSO", "FECHA_INICIO", "FECHA_FIN", "ACTIVO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT 
    -- Vista de TRES_FRANJA_HORARIO, para ver la ocupación de un recurso.
    -- IMPORTANTE: <invariante o decisión clave>. ESTO NO LO HE ENTENDIDO
    --   2026-05-11  Creación inicial de la vista por ANA AMELIA TOLOSA GONZÁLEZ
    
    ID_FRANJA,
    ID_RECURSO,
    FECHA_INICIO,
    FECHA_FIN,
    NVL(ACTIVO, 'N')
FROM CURSONORMADM.TRES_FRANJA_HORARIO;