CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_HORARIO_DIA_BEGTOM" ("ID_HORARIO_DIA", "ID_FRANJA", "ID_RECURSO", "NOMBRE_RECURSO_ES", "NOMBRE_RECURSO_CA", "NOMBRE_RECURSO_EN", "FECHA_INICIO", "FECHA_FIN", "DIA", "HORA_INICIO", "MINUTO_INICIO", "HORA_FIN", "MINUTO_FIN", "ORDEN", "BLOQUEADO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT  /* Vista de los tramos horarios configurados para cada día, tanto de franjas como genéricos por recurso.
   IMPORTANTE: Incluye:
               - ID_FRANJA horario específico de un periodo (puede ser NULL si es genérico)
               - ID_RECURSO recurso genérico.
               - (ID_FRANJA NULL + ID_RECURSO informado): horario por defecto del recurso
   YYYY-MM-DD  AUTOR  Descripción del cambio.
   2016-05-11  BEGOÑA Creación vista */
    HDI.ID_HORARIO_DIA,
    HDI.ID_FRANJA,
    HDI.ID_RECURSO,
    REC.NOMBRE_ES AS NOMBRE_RECURSO_ES,
    REC.NOMBRE_CA AS NOMBRE_RECURSO_CA,
    REC.NOMBRE_EN AS NOMBRE_RECURSO_EN,
    FHO.FECHA_INICIO,
    FHO.FECHA_FIN,
    HDI.DIA,
    HDI.HORA_INICIO,
    HDI.MINUTO_INICIO,
    HDI.HORA_FIN,
    HDI.MINUTO_FIN,
    HDI.ORDEN,
    NVL(HDI.BLOQUEADO,'N') AS BLOQUEADO
   FROM CURSONORMADM.TRES_HORARIO_DIA HDI 
   LEFT JOIN CURSONORMADM.TRES_FRANJA_HORARIO FHO ON HDI.ID_FRANJA=FHO.ID_FRANJA
   LEFT JOIN CURSONORMADM.TRES_RECURSO REC ON FHO.ID_RECURSO=REC.ID_RECURSO;