CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_HORARIO_DIA_JMSBERNABEU" ("ID_HORARIO_DIA", "ID_FRANJA", "ID_RECURSO", "DIA", "HORA_INICIO", "MINUTO_INICIO", "HORA_FIN", "MINUTO_FIN", "BLOQUEADO", "ORDEN") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    HD.ID_HORARIO_DIA,
    HD.ID_FRANJA,
    COALESCE(HD.ID_RECURSO, TF.ID_RECURSO) AS ID_RECURSO,
    HD.DIA,
    HD.HORA_INICIO,
    HD.MINUTO_INICIO,
    HD.HORA_FIN,
    HD.MINUTO_FIN,
    HD.BLOQUEADO,
    HD.ORDEN
FROM CURSONORMADM.TRES_HORARIO_DIA HD
LEFT JOIN CURSONORMADM.TRES_FRANJA_HORARIO TF
    ON TF.ID_FRANJA = HD.ID_FRANJA;