CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_HORARIO_DIA_JAUME" ("ID_HORARIO_DIA", "ID_FRANJA", "ID_RECURSO", "NOMBRE_RECURSO_ES", "NOMBRE_RECURSO_CA", "NOMBRE_RECURSO_EN", "FECHA_INICIO", "FECHA_FIN", "DIA", "HORA_INICIO", "MINUTO_INICIO", "HORA_FIN", "MINUTO_FIN", "BLOQUEADO", "ORDEN") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select /* Vista de VRES_HORARIO_DIA_JAUME.

  2026-05-11  JAUME  creación de la vista.
                       */
    hd.id_horario_dia,
    hd.ID_FRANJA,
    hd.ID_RECURSO,
    R.NOMBRE_ES as NOMBRE_RECURSO_ES, 
    R.NOMBRE_CA as NOMBRE_RECURSO_CA,
    R.NOMBRE_EN as NOMBRE_RECURSO_EN,
    FH.FECHA_INICIO, 
    FH.FECHA_FIN, 
    hd.DIA,
    hd.HORA_INICIO,
    hd.minuto_inicio,
    hd.HORA_FIN,
    hd.minuto_FIN,
    nvl(hd.BLOQUEADO, 'N') as BLOQUEADO,
    HD.ORDEN
from TRES_HORARIO_DIA HD
left join TRES_FRANJA_HORARIO FH on HD.ID_FRANJA = FH.ID_FRANJA
left join TRES_RECURSO R on FH.ID_RECURSO = R.ID_RECURSO;