CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_FRANJA_HORARIO_JMSBERNABEU" ("ID_FRANJA", "ID_RECURSO", "FECHA_INICIO", "FECHA_FIN", "ACTIVO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    ID_FRANJA,
    ID_RECURSO,
    FECHA_INICIO,
    FECHA_FIN,
    ACTIVO
FROM
    CURSONORMADM.TRES_HORARIO_DIA
WHERE
    ACTIVO = 'S';