CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_FRANJA_HORARIO_JAUME" ("ID_FRANJA", "ID_RECURSO", "NOMBRE_RECURSO_ES", "NOMBRE_RECURSO_CA", "NOMBRE_RECURSO_EN", "FECHA_INICIO", "FECHA_FIN", "ACTIVO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select /* Vista de VRES_FRANJA_HORARIO_JAUME.

  2026-05-11  JAUME  creación de la vista.
                       */
    FH.ID_FRANJA, 
    FH.ID_RECURSO, 
    R.NOMBRE_ES as NOMBRE_RECURSO_ES, 
    R.NOMBRE_CA as NOMBRE_RECURSO_CA,
    R.NOMBRE_EN as NOMBRE_RECURSO_EN,
    FH.FECHA_INICIO, 
    FH.FECHA_FIN, 
    FH.ACTIVO
from TRES_FRANJA_HORARIO FH
join TRES_RECURSO R on FH.ID_RECURSO = R.ID_RECURSO;