CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_TIPO_RECURSO" ("ID_TIPO_RECURSO", "CODIGO", "NOMBRE_ES", "NOMBRE_CA", "NOMBRE_EN") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT /* Vista de catalogo de tipos de recurso para clasificar recursos reservables.


   04/03/2026  SERVICIOINFORMATICA  Creacion de la vista.
                       */
  ID_TIPO_RECURSO,
  CODIGO,
  NOMBRE_ES,
  NOMBRE_CA,
  NOMBRE_EN
FROM CURSONORMADM.TRES_TIPO_RECURSO;