CREATE OR REPLACE FORCE EDITIONABLE VIEW "CURSONORMADM"."VRES_RECURSO" ("ID_RECURSO", "ID_TIPO_RECURSO", "NOMBRE_TIPO_RECURSO_ES", "NOMBRE_TIPO_RECURSO_CA", "NOMBRE_TIPO_RECURSO_EN", "NOMBRE_ES", "NOMBRE_CA", "NOMBRE_EN", "DESCRIPCION_ES", "DESCRIPCION_CA", "DESCRIPCION_EN", "FECHA_MODIFICACION", "ACTIVO", "VISIBLE", "GRANULIDAD", "DURACION") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
  R.ID_RECURSO,
  R.ID_TIPO_RECURSO,
  TR.NOMBRE_ES AS NOMBRE_TIPO_RECURSO_ES,
  TR.NOMBRE_CA AS NOMBRE_TIPO_RECURSO_CA,
  TR.NOMBRE_EN AS NOMBRE_TIPO_RECURSO_EN,
  R.NOMBRE_ES,
  R.NOMBRE_CA,
  R.NOMBRE_EN,
  R.DESCRIPCION_ES,
  R.DESCRIPCION_CA,
  R.DESCRIPCION_EN,
  R.FECHA_MODIFICACION,
  NVL(R.ACTIVO, 'N') AS ACTIVO,
  NVL(R.VISIBLE, 'N') AS VISIBLE,
  R.GRANULIDAD,
  R.DURACION
FROM CURSONORMADM.TRES_RECURSO R
LEFT JOIN CURSONORMADM.TRES_TIPO_RECURSO TR
  ON TR.ID_TIPO_RECURSO = R.ID_TIPO_RECURSO;