CREATE TABLE "CURSONORMADM"."TRES_TIPO_BLOQUEO_LUILUC" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CODIGO" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"NOMBRE_ES" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"NOMBRE_VA" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"NOMBRE_EN" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"COLOR" VARCHAR2(7) COLLATE "USING_NLS_COMP", 
	"ORDEN" NUMBER(3,0), 
	"ACTIVO" CHAR(1) COLLATE "USING_NLS_COMP" DEFAULT 'S', 
	 CONSTRAINT "CHK_TTB_CODIGO_NN_LUILUC" CHECK (CODIGO IS NOT NULL) ENABLE, 
	 CONSTRAINT "CHK_TTB_NOMBRE_ES_NN_LUILUC" CHECK (NOMBRE_ES IS NOT NULL) ENABLE, 
	 CONSTRAINT "CHK_TTB_NOMBRE_VA_NN_LUILUC" CHECK (NOMBRE_VA IS NOT NULL) ENABLE, 
	 CONSTRAINT "CHK_TTB_NOMBRE_EN_NN_LUILUC" CHECK (NOMBRE_EN IS NOT NULL) ENABLE, 
	 CONSTRAINT "CHK_TTB_ACTIVO_NN_LUILUC" CHECK (ACTIVO IS NOT NULL) ENABLE, 
	 CONSTRAINT "CHK_TTB_ACTIVO_LUILUC" CHECK (ACTIVO IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CHK_TTB_ORDEN_LUILUC" CHECK (
            ORDEN IS NULL
            OR ORDEN BETWEEN 1 AND 999
        ) ENABLE, 
	 CONSTRAINT "CHK_TTB_COLOR_LUILUC" CHECK (
            COLOR IS NULL
            OR REGEXP_LIKE(
                COLOR,
                '^#[0-9A-Fa-f]{6}$'
            )
        ) ENABLE, 
	 CONSTRAINT "PK_TRES_TIPO_BLOQUEO_LUILUC" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UK_TRES_TIPO_BLOQUEO_CODIGO_LUILUC" UNIQUE ("CODIGO")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;