CREATE TABLE "CURSONORMADM"."TRES_TIPO_BLOQUEO_AFGQ" 
   (	"ID_TIPO_BLOQUEO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CODIGO" VARCHAR2(5) COLLATE "USING_NLS_COMP", 
	"NOMBRE_ES" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"NOMBRE_CA" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"NOMBRE_EN" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"COLOR" VARCHAR2(7) COLLATE "USING_NLS_COMP", 
	"ORDEN" NUMBER, 
	"ACTIVO" VARCHAR2(1) COLLATE "USING_NLS_COMP" DEFAULT 'S' NOT NULL ENABLE, 
	 CONSTRAINT "CK_TRES_TIPO_BLOQUEO_AFGQ_ACTIVO" CHECK (ACTIVO IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_TRES_TIPO_BLOQUEO_AFGQ_COLOR" CHECK (COLOR IS NULL OR REGEXP_LIKE(COLOR, '^#[0-9A-Fa-f]{6}$')) ENABLE, 
	 CONSTRAINT "CK_TRES_TIPO_BLOQUEO_AFGQ_ORDEN" CHECK (ORDEN IS NULL OR ORDEN BETWEEN 1 AND 999) ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  CREATE UNIQUE INDEX "CURSONORMADM"."UK_TRES_TIPO_BLOQUEO_AFGQ_ID_TIPO_BLOQUEO" ON "CURSONORMADM"."TRES_TIPO_BLOQUEO_AFGQ" ("ID_TIPO_BLOQUEO") 
  ;
  CREATE UNIQUE INDEX "CURSONORMADM"."UK_TRES_TIPO_BLOQUEO_AFGQ_CODIGO" ON "CURSONORMADM"."TRES_TIPO_BLOQUEO_AFGQ" ("CODIGO") 
  ;
ALTER TABLE "CURSONORMADM"."TRES_TIPO_BLOQUEO_AFGQ" ADD CONSTRAINT "PK_TRES_TIPO_BLOQUEO_AFGQ_ID_TIPO_BLOQUEO" PRIMARY KEY ("ID_TIPO_BLOQUEO")
  USING INDEX "CURSONORMADM"."UK_TRES_TIPO_BLOQUEO_AFGQ_ID_TIPO_BLOQUEO"  ENABLE;
ALTER TABLE "CURSONORMADM"."TRES_TIPO_BLOQUEO_AFGQ" ADD CONSTRAINT "PK_TRES_TIPO_BLOQUEO_AFGQ_CODIGO" UNIQUE ("CODIGO")
  USING INDEX "CURSONORMADM"."UK_TRES_TIPO_BLOQUEO_AFGQ_CODIGO"  ENABLE;