CREATE TABLE "CURSONORMADM"."VRES_FESTIVOS" 
   (	"FECHA" DATE NOT NULL ENABLE, 
	"NOMBRE_ES" VARCHAR2(200) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"NOMBRE_CA" VARCHAR2(200) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"NOMBRE_EN" VARCHAR2(200) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "PK_VRES_FESTIVOS" PRIMARY KEY ("FECHA")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;